# Docker Compose específico para Coolify
# Usa este archivo cuando despliegues en Coolify

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        JWT_SECRET: ${JWT_SECRET}
        NODEMAILER_USER: ${NODEMAILER_USER}
        NODEMAILER_PASSWORD: ${NODEMAILER_PASSWORD}
        NODEMAILER_SMTP: ${NODEMAILER_SMTP}
        NODEMAILER_PORT: ${NODEMAILER_PORT}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      NODEMAILER_USER: ${NODEMAILER_USER}
      NODEMAILER_PASSWORD: ${NODEMAILER_PASSWORD}
      NODEMAILER_SMTP: ${NODEMAILER_SMTP}
      NODEMAILER_PORT: ${NODEMAILER_PORT}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      PORT: 3000
      HOSTNAME: "0.0.0.0"
    labels:
      # Labels para Coolify v4
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=feniz-trading"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
