services:
  app:
    build:
      context: ../../
      dockerfile: config/docker/dev.Dockerfile
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: bun run dev
