services:
  feniz-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Database
      - DATABASE_URL=postgres://postgres:n84SJBEOEik3wSSojUkwJIu8wUu8EAKuQYdHaWHf5c2QhyQ8qP1k43SOiaLuOW0I@161.132.51.242:5432/feniz
      
      # Authentication
      - BETTER_AUTH_SECRET=99yVjBrOtdUGSVksSqcNXWxLuvTeDVrD
      - JWT_SECRET=hxGRRHH8w/k+6+Bsj9WWXu8517+kciY6Q95PRDfDuE8=
      
      # Site URLs - Cambiar por tu dominio real en Coolify
      - NEXT_PUBLIC_API_URL=${SITE_URL:-http://localhost:3000}
      - NEXTAUTH_URL=${SITE_URL:-http://localhost:3000}
      
      # Google OAuth
      - GOOGLE_CLIENT_ID=88595118272-sg39fpvgrk8gb7tra3o7fuovv2hig82i.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      
      # Email Configuration
      - NODEMAILER_SMTP=mail.estrategiags.com
      - NODEMAILER_PORT=465
      - NODEMAILER_USER=test@estrategiags.com
      - NODEMAILER_PASSWORD=HWmmjDNI234234
      
      # Next.js Production Settings
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    
    # Optimized for Coolify resource management
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'
        reservations:
          memory: 768M
          cpus: '0.5'
    
    # Logging optimized for Coolify
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    
    # Labels for Coolify identification
    labels:
      - "coolify.managed=true"
      - "coolify.name=feniz-trading-platform"
      - "coolify.type=application"

networks:
  default:
    driver: bridge