[variables]
BUN_VERSION = "1.0.0"

[phases.setup]
nixPkgs = ["curl", "unzip"]
cmds = [
  "curl -fsSL https://bun.sh/install | bash",
  "export PATH=\"$HOME/.bun/bin:$PATH\""
]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"