# Force nixpacks to use ONLY Bun - no npm
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install --production"]
paths = ["/app/node_modules/.bin"]
cacheDirectories = ["/root/.bun", "/app/node_modules"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"

[variables]
NODE_VERSION = "20"
PACKAGE_MANAGER = "bun"
BUN_INSTALL_CACHE_DIR = "/tmp/bun-cache"
NPM_CONFIG_PRODUCTION = "false"
