[variables]
BUN_VERSION = "latest"

[phases.setup]
nixPkgs = ["curl", "bash"]

[phases.install]
cmds = [
  "curl -fsSL https://bun.sh/install | bash",
  "export PATH=\"/root/.bun/bin:$PATH\" && bun install --frozen-lockfile"
]

[phases.build]
cmds = [
  "export PATH=\"/root/.bun/bin:$PATH\" && bun run build"
]

[start]
cmd = "export PATH=\"/root/.bun/bin:$PATH\" && bun run start"