version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: config/docker/dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app             # Hot reload: reflejar cambios locales
      - /app/node_modules  # Evita conflictos con node_modules locales
    environment:
      - NODE_ENV=development
